# Spark Master
spark.master                     spark://spark-master:7077

# HDFS connection
spark.hadoop.fs.defaultFS        hdfs://namenode:9000

# Hive Metastore integration
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083

# Performance
spark.sql.shuffle.partitions     4
spark.default.parallelism        4

# History server
spark.eventLog.enabled           false
